version: '3.9'

services:

  bot:
    build:
      context: ../bot
    env_file:
      - ../bot/.env-non-dev
    container_name: bot
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ../bot/.env-non-dev
    command: --port 2000
    expose:
      - 2000

  postgres:
    image: postgres:15
    container_name: database
    env_file:
      - ../bot/.env-non-dev
    command: -p 1000
    expose:
      - 1000
  
